# Generated by Django 3.0.7 on 2020-06-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200630_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='premise_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='premise_number'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='street',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='street'),
        ),
    ]
