# Generated by Django 3.0.7 on 2020-07-01 20:26

from django.db import migrations, models
import django.db.models.deletion

from core.migration_scripts import create_default_roles, reverse_create_default_roles

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200630_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('user', 'User'), ('mod', 'Moderator'), ('administrator', 'Administrator')], max_length=32, verbose_name='Role name')),
                ('index', models.IntegerField(default=20)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.UserRole'),
        ),
        migrations.RunPython(create_default_roles, reverse_create_default_roles)
    ]
