# Generated by Django 3.0.7 on 2020-07-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200701_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Phone'),
        ),
    ]
